// Verify touch centers, route state and backwards seeking in the authored mobile UI.
const fs=require('fs'),path=require('path'),os=require('os');
const cache=path.join(os.homedir(),'.npm','_npx');const mods=fs.readdirSync(cache).map(d=>path.join(cache,d,'node_modules','puppeteer-core')).filter(p=>fs.existsSync(path.join(p,'package.json')));const puppeteer=require(mods[0]);
(async()=>{const browser=await puppeteer.launch({executablePath:'/Applications/Google Chrome.app/Contents/MacOS/Google Chrome',headless:true,args:['--allow-file-access-from-files']});try{
const p=await browser.newPage();await p.setViewport({width:1080,height:1920});const root=path.resolve('videos/sideway');const html=fs.readFileSync(path.join(root,'compositions/frames/02-one-walk.html'),'utf8').replace('<template>','').replace('</template>','');
const file=path.join(root,'.hyperframes/geometry-qa.html');fs.writeFileSync(file,`<!doctype html><html><head><base href="file://${root}/"><style>html,body{margin:0;width:1080px;height:1920px}</style><script src="assets/gsap.min.js"></script><script>window.__timelines={};</script></head><body>${html}</body></html>`);await p.goto('file://'+file);await p.evaluate(()=>document.fonts.ready);
const clicks=[];for(const [t,target,touch] of [[1.2,'s2-selected','s2-touch-time'],[3.2,'s2-create','s2-touch-create'],[13.2,'s2-start','s2-touch-start']])clicks.push(await p.evaluate(({t,target,touch})=>{window.__timelines['02-one-walk'].seek(t);const b=document.getElementById(target).getBoundingClientRect(),c=document.getElementById(touch).getBoundingClientRect(),point={x:c.x+c.width/2,y:c.y+c.height/2};return{time:t,target,point,bounds:{x:b.x,y:b.y,w:b.width,h:b.height},inside:point.x>b.x&&point.x<b.right&&point.y>b.y&&point.y<b.bottom};},{t,target,touch}));
const states=[];for(const t of [0,2,5,10,14.5,0,14.5,2])states.push(await p.evaluate(t=>{window.__timelines['02-one-walk'].seek(t);const o=id=>+getComputedStyle(document.getElementById(id)).opacity;return{t,initial:o('s2-initial'),selected:o('s2-selected'),nav:o('s2-nav'),summary:o('s2-summary'),pins:[0,1,2].map(i=>o('s2-pin'+i)),dash:+gsap.getProperty('#s2-route','strokeDashoffset')};},t));
if(clicks.some(x=>!x.inside)||states[0].selected!==0||states[1].selected!==1||states[2].initial!==0||states[3].pins.some(x=>x!==1)||states[4].nav!==1||JSON.stringify(states[0])!==JSON.stringify(states[5])||JSON.stringify(states[4])!==JSON.stringify(states[6])||JSON.stringify(states[1])!==JSON.stringify(states[7]))throw Error('Mobile UI interaction or reversible seeking failed');
const result={clicks,states,walking_minutes:22,linger_minutes:38,total_minutes:60,route:'illustrative neighborhood, not live geography'};if(result.walking_minutes+result.linger_minutes!==result.total_minutes)throw Error('Time budget mismatch');fs.writeFileSync('artifacts/library-loop-14/geometry.json',JSON.stringify(result,null,2)+'\n');console.log('Three touch targets, route state,60-minute budget and reversible seeking passed.');
}finally{await browser.close()}})();
